### ISSUE TITLE
Implement pagination in 'Get list of entities' requests

### ISSUE THREAD

**Issue by KhusainovFarrukh** [Hamdam23/bookee#10]

**Comment by Hamdam23** [comment]
![image](https://user-images.githubusercontent.com/90045606/188270390-234ba1c3-f50d-4781-991d-1ec4ce9f59c1.png)

Let's talk about what should I return on response.
If response details on the picture is fine, I'll implement the logic to entire project.

An interesting repo:
https://github.com/bezkoder/spring-boot-jpa-paging-sorting

**Comment by Hamdam23** [comment]
An interesting repo:
https://github.com/bezkoder/spring-boot-jpa-paging-sorting

**Comment by KhusainovFarrukh** [comment]
> Let's talk about what should I return on response. If response details on the picture is fine, I'll implement the logic to entire project.

I think it's ok, but I suggest removing separate 'pageable' JSON object for page details. You can write page details directly on parent JSON object:

```
{
    "items": [ ],
    "page": 3,
    "next_page": 4,
    "prev_page": 2,
    "total_items": 47,
    "total_pages" : 5,
    "page_size": 10
}
```

**Comment by Hamdam23** [comment]
This repo looks good:
https://github.com/Mozenn/spring-boot-rest-api-with-pagination-and-sorting/tree/main/src/main/java/com/mozen/springbootpaginationandsorting

**Comment by Hamdam23** [comment]
Test implementation is done on 65cf27ae483057933119e51a34004bcf9610559a for Book API, and will be added to the whole project.
