### ISSUE TITLE
Access and refresh tokens expire time logic not working

### ISSUE THREAD

**Issue by KhusainovFarrukh** [Hamdam23/bookee#12]
Access and refresh tokens expire time milliseconds in login and refresh-token endpoints are not changing. Every time expire time of the first token is sent on response. Also if the username and password are not changed, the token will be the same as the previous token

Steps to reproduce the problem:
1. Send a login request for A user
2. Save expire time of access and refresh tokens somewhere
3. Resend login request for A user
4. You can see access, refresh tokens and their expire time are equal to values in the first response
5. Send login request for B user
6. This time access, and refresh tokens changed, but their expire time don't.

The above error and steps also apply to refresh token request.

**Comment by Hamdam23** [comment]
First opinion: I am giving username and password for generating token. So if it is the same username and password then token is remaining the same.
Possible solution: Maybe giving smth unique when giving username and password can be the answer?

**Comment by Hamdam23** [comment]
Implemented in 4f311af3da4db5a80434ce9b7170936633c3ee01 and waiting for getting merged to master.
