### ISSUE TITLE
Error 500 on invalid type image file upload

### ISSUE THREAD

**Issue by KhusainovFarrukh** [Hamdam23/bookee#13]
![image](https://user-images.githubusercontent.com/68108113/188199825-a97789c8-b5ce-47a0-85f1-9ba5228e52aa.png)

**Comment by Hamdam23** [comment]
https://stackoverflow.com/questions/65149707/custom-constraintvalidator-message-with-custom-http-error-response 
this is exactly the same problem as mine, it alse can not change the status of the response :(

**Comment by Hamdam23** [comment]
fixed on commit: 7fd2d014442819fcb83f29b8b9dcaab87af54c12
