### ISSUE TITLE
User with non default role (author) can't see his/her role requests

### ISSUE THREAD

**Issue by KhusainovFarrukh** [Hamdam23/bookee#14]
![image](https://user-images.githubusercontent.com/68108113/188202625-de9a360e-4543-4700-8761-8adfafa77b22.png)

**Comment by Hamdam23** [comment]
As a logic of the bookee - only Users with 'user' role can request 'author' role.
No access for requesting for 'admin' role or Downgrading role.

**Comment by KhusainovFarrukh** [comment]
What if admin changes names of the roles: 'user' to 'reader', 'author' to 'writer'? Is role dynamic?

**Comment by Hamdam23** [comment]
Implemented in e14ba56c4c2ddfe569d07f16dfaf027cca679a8b and waiting for getting merged to master.
