### ISSUE TITLE
500 error is thrown when 401 should be in charge

### ISSUE THREAD

**Issue by Hamdam23** [Hamdam23/bookee#15]
500 error status is returning when token is invalid/expired/not-given on endpionts.

![image](https://user-images.githubusercontent.com/90045606/190479073-28ee32b5-7b92-44ed-9cdb-abce92cd61d0.png)

Quick summery: 
- Handling AuthenticationException will handle invalid credentials(username/password).
- Handling AccessDeniedException is used for method level security such as securing a method for specific roles or authorities.

**Comment by Hamdam23** [comment]
Token belongs to the User on 'user' role who does not have access.
Look there should be 403 Access Denied!

![image](https://user-images.githubusercontent.com/90045606/190630912-20b3a8bc-f198-46bd-baa5-431c48ba2b47.png)

**Comment by KhusainovFarrukh** [comment]
The bug is fixed. But I suggest using only one method of handling security exceptions. Choose one: custom exceptions (via ExceptionHandler) or  security handlers (AccessDeniedHandler & AuthenticationEntryPoint)
