### ISSUE TITLE
Image upload not working on deployment (heroku)

### ISSUE THREAD

**Issue by KhusainovFarrukh** [Hamdam23/bookee#9]
https://safe-hollows-41964.herokuapp.com/api/v1/images/upload is not working.

![image](https://user-images.githubusercontent.com/68108113/188108335-f761849b-4891-489d-beef-533bd4c28c80.png)

**Comment by KhusainovFarrukh** [comment]
@Hamdam23 any news?

**Comment by Hamdam23** [comment]
![image](https://user-images.githubusercontent.com/90045606/207609702-902c9ad3-5e2e-46ad-adf9-739ccdd74f13.png)
